#!/bin/bash
echo "=== KIRA Backend CRUD APIs - Implementation Verification ==="
echo ""
echo "📁 Files Created:"
echo "Services:"
test -f src/services/HRContactService.ts && echo "  ✅ HRContactService.ts" || echo "  ❌ HRContactService.ts"
test -f src/services/DailyLogService.ts && echo "  ✅ DailyLogService.ts" || echo "  ❌ DailyLogService.ts"
test -f src/services/ApplyQueueService.ts && echo "  ✅ ApplyQueueService.ts" || echo "  ❌ ApplyQueueService.ts"
test -f src/services/PlannerTaskService.ts && echo "  ✅ PlannerTaskService.ts" || echo "  ❌ PlannerTaskService.ts"
echo ""
echo "Routes:"
test -f src/routes/hrcontacts.ts && echo "  ✅ hrcontacts.ts" || echo "  ❌ hrcontacts.ts"
test -f src/routes/logs.ts && echo "  ✅ logs.ts" || echo "  ❌ logs.ts"
test -f src/routes/queue.ts && echo "  ✅ queue.ts" || echo "  ❌ queue.ts"
test -f src/routes/planner.ts && echo "  ✅ planner.ts" || echo "  ❌ planner.ts"
echo ""
echo "📊 Compilation Status:"
npm run build > /dev/null 2>&1 && echo "  ✅ TypeScript compilation successful" || echo "  ❌ Compilation failed"
echo ""
echo "🔍 Dist Files Generated:"
test -f dist/services/HRContactService.js && echo "  ✅ HRContactService.js" || echo "  ❌ Missing"
test -f dist/services/DailyLogService.js && echo "  ✅ DailyLogService.js" || echo "  ❌ Missing"
test -f dist/services/ApplyQueueService.js && echo "  ✅ ApplyQueueService.js" || echo "  ❌ Missing"
test -f dist/services/PlannerTaskService.js && echo "  ✅ PlannerTaskService.js" || echo "  ❌ Missing"
test -f dist/routes/hrcontacts.js && echo "  ✅ hrcontacts.js" || echo "  ❌ Missing"
test -f dist/routes/logs.js && echo "  ✅ logs.js" || echo "  ❌ Missing"
test -f dist/routes/queue.js && echo "  ✅ queue.js" || echo "  ❌ Missing"
test -f dist/routes/planner.js && echo "  ✅ planner.js" || echo "  ❌ Missing"
echo ""
echo "🔐 Routes Mounted in index.ts:"
grep -q "hrContactsRoutes" src/index.ts && echo "  ✅ HR Contacts route imported" || echo "  ❌ Missing"
grep -q "logsRoutes" src/index.ts && echo "  ✅ Logs route imported" || echo "  ❌ Missing"
grep -q "queueRoutes" src/index.ts && echo "  ✅ Queue route imported" || echo "  ❌ Missing"
grep -q "plannerRoutes" src/index.ts && echo "  ✅ Planner route imported" || echo "  ❌ Missing"
echo ""
echo "📝 Validation Schemas Added:"
grep -q "DailyLogSchema" src/middleware/validation.ts && echo "  ✅ DailyLogSchema" || echo "  ❌ Missing"
grep -q "PlannerTaskSchema" src/middleware/validation.ts && echo "  ✅ PlannerTaskSchema" || echo "  ❌ Missing"
echo ""
echo "📊 Line Counts:"
wc -l src/services/HRContactService.ts src/services/DailyLogService.ts src/services/ApplyQueueService.ts src/services/PlannerTaskService.ts | tail -1
wc -l src/routes/hrcontacts.ts src/routes/logs.ts src/routes/queue.ts src/routes/planner.ts | tail -1
echo ""
echo "✨ Implementation Complete!"
